### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by silentaim** [silentaim/stratego#51]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at game.player.AIPlayer.guessesBoard(AIPlayer.java:200)
	at game.player.AIPlayer.nextMove(AIPlayer.java:488)

Seems to happen when the spy captures the skull king. After the successful capture, the null pointer is thrown. At this point the game gets stuck on the enemy's turn, but the enemy doesn't move.

**Comment by silentaim** [comment]
Patched on latest feature
